---
# tasks file for s3-copy
- name: Ensure boto and boto3 modules are installed
  pip:
    name:
      - boto3
      - botocore
    extra_args: --upgrade

- name: setup local dest directories
  become: false
  file: 
    path: "{{ s3_local_dir }}/{{ item | dirname }}"
    state: directory
  with_items: "{{ s3_objects }}"

- name: download objects from s3
  become: false
  aws_s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ item }}"
    dest: "{{ s3_local_dir }}/{{ item }}"
    overwrite: different
    mode: get
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
  with_items: "{{ s3_objects }}"
